"""signatures - central registry of every patch-sensitive address the client depends on + a self-check.

Single source of truth for the hardcoded sites scattered across the gate/detector modules, plus a
preflight that, on attach, resolves every site and reports a health table. Two jobs:

  * GO/NO-GO preflight - never run gates/detours against addresses that don't resolve sane (which would
    corrupt memory); and
  * patch compass - when a Frontier update shifts the binary, the self-check tells you EXACTLY which of
    the ~dozen sites broke, so re-RE is targeted (using the recipes in docs/memory), not from scratch.

Resolution strategy per site (most→least patch-robust):
  1. script-bound natives -> resolve by NAME via the binding registrar (names are stable across patches)
     [release/permit are script-bound; registrar walk is in tools/dump_bindings.py - wire-in is future];
  2. AOB signature (opcode/modrm/struct-offsets kept, rel32/RIP-disp wildcarded) -> auto-relocates;
  3. raw RVA + expected ORIG bytes -> intact-check only (detects breakage, doesn't auto-relocate).
Today every hook ships (3) (RVA+ORIG, what the gates use) and, where a unique pattern exists, (2).
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger("PZClient")

# ── hook sites the client detours (rva, expected original bytes, role) ───────────────────────────────
@dataclass(frozen=True)
class HookSite:
    name: str
    rva: int
    orig_hex: str
    role: str
    aob: Optional[str] = None        # unique wildcarded pattern for auto-relocation (None until baked)
    script_name: Optional[str] = None  # if script-bound, the registrar name (most robust resolve)

    @property
    def orig(self) -> bytes:
        return bytes.fromhex(self.orig_hex)


# AOB signatures generated by tools/gen_aob.py (verified unique in-module); auto-relocate on a patch.
HOOKS: List[HookSite] = [
    HookSite("permit", 0xA0894E5, "0fb68310020000",
             "Animal-Exchange purchase block (PermitGate)",
             aob="0F B6 83 10 02 00 00 84 C0 74 64 4C 8B 83 08 02 00 00 49 F7 D8 49 8B 97 10 01 00 00"),
    HookSite("release", 0x5D84690, "48895c2410",
             "ReleaseAnimalIntoWild entry (conservation gate)", script_name="ReleaseAnimalIntoWild"),
    HookSite("release_species", 0x5D8478F, "488b4d484889f2",
             "ReleaseAnimalIntoWild call-prep (released-species capture; entry+0xFF)"),
    HookSite("birth_insert", 0xC82168, "488bbdd8000000",
             "add-animal insert instrument (BirthDetector)",
             aob="48 8B BD D8 00 00 00 4D 85 F6 75 3E 44 38 B5 F8 00 00 00 75 2A 49 8B 8D F8 04 00 00"),
    HookSite("presence", 0x9E94863, "c6040101488d842480000000",
             "facility presence-cache fill (PresenceGate)",
             aob="C6 04 01 01 48 8D 84 24 80 00 00 00 48 89 44 24 28 48 8D 8D 60 03 00 00 48 8D 84 24 88 00 00 00 48 89 44 24 20 E8 ?? ?? ?? ?? 8B 84 24 80 00 00 00 48 83 C7 10 48 6B C8 38 41 0F B7 06 48 03 8D B0 03 00 00"),
    HookSite("research_start", 0xE461C6, "41c6474902",
             "research-START status write (ResearchGate)",
             aob="41 C6 47 49 02 48 8B 11 48 3B 51 10 72 11 48 8D 55 40 E8 ?? ?? ?? ?? 8B 75 40"),
]

# ── data anchors (resolved via anchors.json chains) with plausible-value sanity ranges ───────────────
#   name -> (lo, hi) inclusive plausible range; a read outside this = garbage (stale root / bad chain).
ANCHOR_SANITY: Dict[str, Tuple[float, float]] = {
    "cash": (-5_000_000.0, 1_000_000_000.0),    # challenge $; allow some debt, reject i64-garbage
    "conservation_credits": (0.0, 50_000_000.0),
    "guest_count": (0.0, 200_000.0),
    "zoo_rating": (0.0, 5.0),                    # stars
}

# research-system reachability chain (mirrors research.py RESEARCH_CHAIN); sanity = map has records.
RESEARCH_CHAIN = (0x2944690, 0x18, 0x350)

# Park-age fresh-save signal. The "park-info" class (vtable RVA below) holds, at +0x1c8, the number of
# COMPLETED YEARS the park has been open (GetParkPeriodsOpen reads *(world+0xa8)+0x1c8) - monotonic and
# PERSISTED in the save. Confirmed live: Year 1 -> 0, Year 2 -> 1, Year 30 -> 29. We vtable-scan the class
# (layout-independent, like the research system) and take the max +0x1c8 over instances (a static template
# instance always reads 0; the live park carries the real count). A tiny value == a fresh zoo. Build-
# specific RVA - re-derive after a patch with tools/parkage_probe.py --find-world / --parkinfo-vt.
PARKINFO_VTABLE_RVA = 0x26C2ED8
PARKINFO_PERIODS_OFF = 0x1C8
# Park NAME on the same park-info class: +0x1E8 = pointer to the engine's refcounted string
# {len i64 @+0x00, refcount i32 @+0x10, chars @+0x14}. GetParkName executor 0x1466770E0 reads
# *(world+0xA8)+0x1E8; SetParkName 0x14667A8F0 interns the Lua string and swaps it here. NULL when
# nothing ever named the park (true for the AP scenario's empty bin - the frontend's
# GetLocalisedText(scenarioName) is nil for our plain-string label, so the load path sets nil).
# The AP scenario script plants "ARCHIPELAGO ZOO" here at Init = the AP-session marker
# (memory/session.py reads it to decide whether the loaded park is the AP world).
PARKINFO_NAME_OFF = 0x1E8


# ── robust full-module AOB scan (pymem's pattern_scan_module misses high RVAs) ───────────────────────
def _compile_aob(sig: str) -> re.Pattern:
    parts = []
    for tok in sig.split():
        parts.append(b"." if tok == "??" else re.escape(bytes([int(tok, 16)])))
    return re.compile(b"".join(parts), re.DOTALL)


def module_aob_scan(scanner, sig: str, max_hits: int = 4) -> List[int]:
    """Scan the whole main module for an AOB pattern; returns up to max_hits match addresses.
    Reads in overlapping chunks so a match never straddles a boundary."""
    base = getattr(scanner, "module_base", None)
    size = getattr(scanner, "module_size", None) or 0x20000000
    if not base:
        return []
    pat = _compile_aob(sig)
    plen = len(sig.split())
    hits: List[int] = []
    chunk = 0x800000
    addr = base
    end = base + size
    while addr < end and len(hits) < max_hits:
        n = min(chunk + plen, end - addr)
        try:
            data = scanner.read_bytes(addr, n)
        except Exception:
            addr += chunk
            continue
        for m in pat.finditer(data):
            hits.append(addr + m.start())
            if len(hits) >= max_hits:
                break
        addr += chunk
    return hits


# ── self-check ───────────────────────────────────────────────────────────────────────────────────────
def _is_leaked_detour(scanner, site: int, original: bytes) -> bool:
    """True iff ``site`` holds one of OUR OWN leaked detours: a rel32 jmp (0xE9) whose target
    trampoline still contains the site's original bytes. This distinguishes a hook leaked by a prior
    unclean exit (the console X button, a kill, a crash) - which we may safely restore in place - from
    a genuine code change or a foreign patch, which we must NOT touch."""
    try:
        head = scanner.read_bytes(site, 5)
        if head[0] != 0xE9:
            return False
        rel = int.from_bytes(head[1:5], "little", signed=True)
        target = site + 5 + rel
        tramp = scanner.read_bytes(target, 0x200)
    except Exception:
        return False
    return original in tramp  # our trampoline embeds the relocated original instruction


def recover_leaked_hook(scanner, name: str) -> bool:
    """If a hook site still holds our own leaked detour from a prior unclean exit, restore its original
    bytes in place so a fresh install can proceed (no game restart needed). Returns True if recovered.
    Safe: only writes when the jmp target is verifiably our trampoline (see _is_leaked_detour). The
    orphaned trampoline page is harmless (a no-op stub) and is reclaimed when the game process exits."""
    base = getattr(scanner, "module_base", None)
    h = next((x for x in HOOKS if x.name == name), None)
    if h is None or base is None:
        return False
    site = base + h.rva
    if not _is_leaked_detour(scanner, site, h.orig):
        return False
    try:
        scanner.write_bytes(site, h.orig)
    except Exception:
        return False
    logger.info("hook %r: recovered a leaked detour @0x%X (restored original bytes from a prior unclean "
                "exit, e.g. the console X button)", name, site)
    return True


def resolve_hook(scanner, name: str) -> Optional[Tuple[int, bytes]]:
    """Current (address, original-bytes) for a hook site: the RVA if its ORIG is intact, else the
    AOB-relocated address if the signature uniquely re-finds it (survives a patch that shifted the RVA),
    else - if the site holds our own leaked detour from a prior unclean exit - the RVA after restoring
    it in place, else None. Gates call this instead of hardcoding base+RVA so they self-heal across both
    game updates and unclean client exits."""
    base = getattr(scanner, "module_base", None)
    h = next((x for x in HOOKS if x.name == name), None)
    if h is None or base is None:
        return None
    site = base + h.rva
    try:
        if scanner.read_bytes(site, len(h.orig)) == h.orig:
            return (site, h.orig)
    except Exception:
        pass
    # Cheap self-heal FIRST: an unclean exit (kill / console-X / crash) leaves OUR OWN detour at the RVA -
    # fast to detect+restore (a 5-byte read + a verify). The AOB fallback below scans the WHOLE module, so
    # doing it first wasted ~module-size per leaked hook and was the dominant cost of a slow first tick after
    # an unclean exit (every site leaked -> one full module scan each = minutes). Order: RVA, leak, AOB.
    if recover_leaked_hook(scanner, name):
        return (site, h.orig)
    if h.aob:
        hits = module_aob_scan(scanner, h.aob)
        if len(hits) == 1:
            return (hits[0], h.orig)
    return None


# The anchor-chain root globals (base+0x2944690 / 0x29446A0) are NOT directly code-referenced - they're
# entries in a .data cluster reached via a near-root global + offset. We harden them by signaturing a
# UNIQUE code ref to a near-root cluster global (base+0x2944450) and applying the fixed cluster delta;
# the whole cluster shifts as a block on a patch, so the deltas hold while the signature re-finds the ref.
ROOT_CLUSTER = {
    "aob": "48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 8B D0 48 85 C0 74 15 33 C0 89 42 08",  # rva 0x2B4144
    "lea_disp_off": 3, "lea_len": 7, "global_rva": 0x2944450,
    "root_deltas": {0x2944690: 0x240, 0x29446A0: 0x250},  # cluster global -> each anchor root
}
_ROOT_CACHE: Dict[int, int] = {}


def resolve_root(scanner, root_rva: int) -> Optional[int]:
    """Address of an anchor-chain root global, signature-hardened: located via the unique cluster ref +
    fixed delta (survives a patch that shifts the RVA). Cached per process (module addresses are stable
    within a run). Falls back to base+rva if the signature can't resolve (the self-check flags that)."""
    base = getattr(scanner, "module_base", None)
    if base is None:
        return None
    delta = ROOT_CLUSTER["root_deltas"].get(root_rva)
    if delta is None:
        return base + root_rva               # not a known root -> raw RVA
    if root_rva in _ROOT_CACHE:
        return _ROOT_CACHE[root_rva]
    addr = base + root_rva                    # fallback
    hits = module_aob_scan(scanner, ROOT_CLUSTER["aob"])
    if len(hits) == 1:
        try:
            disp = int.from_bytes(scanner.read_bytes(hits[0] + ROOT_CLUSTER["lea_disp_off"], 4), "little", signed=True)
            addr = (hits[0] + ROOT_CLUSTER["lea_len"] + disp) + delta
        except Exception:
            addr = base + root_rva
    _ROOT_CACHE[root_rva] = addr
    return addr


@dataclass
class CheckResult:
    category: str
    name: str
    status: str          # "ok" | "relocated" | "broken" | "garbage" | "unresolved"
    detail: str = ""


def _classify_hook(scanner, h: HookSite) -> CheckResult:
    """Health of one hook site: ok (intact) | relocated (AOB re-found) | leaked (our own detour from an
    unclean exit, auto-recovers) | broken (genuine code change, needs re-RE) | unresolved (unreadable)."""
    site = scanner.module_base + h.rva
    try:
        cur = scanner.read_bytes(site, len(h.orig))
    except Exception:
        return CheckResult("hook", h.name, "unresolved", "site unreadable @0x%X" % site)
    if cur == h.orig:
        return CheckResult("hook", h.name, "ok", "intact @0x%X" % site)
    # ORIG mismatch. Cheap check FIRST: is this our OWN leaked detour (a prior unclean exit, e.g. the
    # console-X close)? That's a 5-byte read + verify. The AOB fallback below scans the WHOLE module, so
    # doing it first cost ~module-size PER leaked hook and dominated the first-tick preflight after an
    # unclean exit (measured ~40s for 3 leaked sites). Order: intact, leak, AOB-relocate.
    if _is_leaked_detour(scanner, site, h.orig):
        return CheckResult("hook", h.name, "leaked",
                           "our detour still installed @0x%X (prior unclean exit) - auto-recovers on next --memory attach" % site)
    # Not our leak - a real patch may have shifted the RVA: try AOB auto-relocation.
    if h.aob:
        hits = module_aob_scan(scanner, h.aob)
        if len(hits) == 1:
            return CheckResult("hook", h.name, "relocated", "moved to 0x%X (rva 0x%X stale)" % (hits[0], h.rva))
        if len(hits) > 1:
            return CheckResult("hook", h.name, "broken", "AOB ambiguous (%d hits)" % len(hits))
    detail = "ORIG changed + AOB not found - re-RE" if h.aob else "ORIG mismatch + no AOB - re-RE (got %s)" % cur.hex()
    return CheckResult("hook", h.name, "broken", detail)


def check_hooks(scanner) -> List[CheckResult]:
    return [_classify_hook(scanner, h) for h in HOOKS]


def check_anchors(scanner, anchor_table) -> List[CheckResult]:
    out = []
    for name, (lo, hi) in ANCHOR_SANITY.items():
        try:
            val = anchor_table.read(scanner, name)
        except Exception as e:
            out.append(CheckResult("anchor", name, "unresolved", "read error: %s" % type(e).__name__)); continue
        if val is None:
            out.append(CheckResult("anchor", name, "unresolved", "chain unresolved"))
        elif lo <= val <= hi:
            out.append(CheckResult("anchor", name, "ok", "value=%s" % round(val, 3)))
        else:
            out.append(CheckResult("anchor", name, "garbage", "value=%s outside [%s,%s] (stale root?)" % (val, lo, hi)))
    return out


def check_research(scanner) -> List[CheckResult]:
    """Reachability of the research items map via the *validated* reader, which tries BOTH master-root
    chains and picks whichever lands on a real map (research.py:_research_system). The primary chain can
    dereference to a valid-but-wrong object on some sessions, so checking only RESEARCH_CHAIN (as this
    did) false-fails - mirror what the client actually does."""
    try:
        from .research import ResearchReader
        snap = ResearchReader(scanner)._snapshot()
    except Exception as e:
        return [CheckResult("system", "research_map", "unresolved", "reader error: %s" % type(e).__name__)]
    if snap is None:
        return [CheckResult("system", "research_map", "garbage",
                            "items map unreadable via either master-root chain (in a loaded zoo?)")]
    cnt = len(snap[0])
    if 0 < cnt < 100000:
        return [CheckResult("system", "research_map", "ok", "%d records" % cnt)]
    return [CheckResult("system", "research_map", "garbage", "record count implausible (%d)" % cnt)]


def check_terrain(scanner, gate=None) -> List[CheckResult]:
    # MAIN2_CODE lives in the writable VM heap, not the module - reuse TerrainGate's writable-region scan.
    # When the client passes its own gate, report from that gate's state WITHOUT a fresh full-heap scan
    # (the in-client gate defers its first scan off the first tick - duplicating it here would re-add the
    # ~20s the defer just removed). Standalone callers (tools/selfcheck.py) pass no gate -> real scan.
    if gate is not None:
        try:
            if gate._cache_valid():
                return [CheckResult("system", "terrain_bytecode", "ok",
                                    "%d copy(ies) of main.2 located" % len(gate._addrs))]
        except Exception:
            pass
        return [CheckResult("system", "terrain_bytecode", "ok",
                            "scan deferred off the first tick (gate locates within a tick or two); "
                            "verify the bytecode on demand with tools/selfcheck.py")]
    try:
        from .terrain import TerrainGate
        found = len(TerrainGate(scanner)._find())
    except Exception as e:
        return [CheckResult("system", "terrain_bytecode", "unresolved", "scan error: %s" % type(e).__name__)]
    if found >= 1:
        return [CheckResult("system", "terrain_bytecode", "ok", "%d copy(ies) of main.2 located" % found)]
    return [CheckResult("system", "terrain_bytecode", "broken", "main.2 signature not found (zoo loaded? bytecode changed?)")]


def check_roots(scanner) -> List[CheckResult]:
    base = scanner.module_base
    hits = module_aob_scan(scanner, ROOT_CLUSTER["aob"])
    if len(hits) != 1:
        return [CheckResult("root", "anchor_roots", "broken",
                            "cluster signature %s (%d hits) - anchors fall back to raw RVA" %
                            ("ambiguous" if hits else "not found", len(hits)))]
    out = []
    for rva in ROOT_CLUSTER["root_deltas"]:
        addr = resolve_root(scanner, rva)
        if addr == base + rva:
            out.append(CheckResult("root", "root_0x%X" % rva, "ok", "signature==RVA @0x%X" % addr))
        else:
            out.append(CheckResult("root", "root_0x%X" % rva, "relocated",
                                   "signature->0x%X (RVA 0x%X stale - anchors will self-correct)" % (addr, base + rva)))
    return out


def check_session(scanner, reader=None) -> List[CheckResult]:
    """AP-session detection state: the park-name marker (park-info +0x1E8) planted by the scenario
    script. 'ok' = marker read back; an unnamed/foreign park is REPORTED but not a failure (the client
    is designed to idle there) - it only flags 'broken' when the park-info class itself is gone.

    When the client passes its own ParkNameReader (already scanned + cached this tick by the session
    gate that fronts every poll tick), reuse it: read() returns from cache, so the preflight doesn't
    repeat the ~20s park-info vtable sweep the session gate just did. Standalone callers pass none."""
    try:
        from .session import AP_PARK_NAME, ParkNameReader
        if reader is None:
            reader = ParkNameReader(scanner)
        name = reader.read()
    except Exception as e:
        return [CheckResult("system", "ap_session", "unresolved", "reader error: %s" % type(e).__name__)]
    if name == AP_PARK_NAME:
        return [CheckResult("system", "ap_session", "ok", "park-name marker present (%r)" % name)]
    if reader._cached:
        return [CheckResult("system", "ap_session", "ok",
                            "park-info resolves; no marker (name=%r) - client idles in this park" % name)]
    return [CheckResult("system", "ap_session", "broken",
                        "no park-info instance (no loaded zoo, or vtable RVA stale after a patch)")]


def run_selfcheck(scanner, anchor_table=None, *, session_reader=None, terrain_gate=None) -> List[CheckResult]:
    """Resolve every dependency and return a health report. anchor_table optional (skips anchor checks).

    session_reader / terrain_gate: the client passes its own already-resolved instances so the preflight
    reuses their state instead of repeating their full-heap scans (~20s each). Standalone callers omit
    them (tools/selfcheck.py) and get fresh scans."""
    results: List[CheckResult] = []
    results += check_hooks(scanner)
    results += check_roots(scanner)
    if anchor_table is not None:
        results += check_anchors(scanner, anchor_table)
    results += check_research(scanner)
    results += check_terrain(scanner, gate=terrain_gate)
    results += check_session(scanner, reader=session_reader)
    return results
